kind: pipeline
name: default

steps:
## Docker Image Build and push
- name: DockerImageCreation  
  image: plugins/docker
  environment:
      AUTH_ID:
        from_secret: AUTH_ID
      AUTH_TOKEN:
        from_secret: AUTH_TOKEN
      SOURCE:
        from_secret: SOURCE
  settings:
    username: ecointet
    password:
      from_secret: ecointet-docker-hub-password
    build_args_from_env:
        - AUTH_ID
        - AUTH_TOKEN
        - SOURCE
    repo: ecointet/sms-server
    dockerfile: Dockerfile
    tag: "0.2"